{
  "openapi": "3.0.1",
  "info": {
    "title": "Default module",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/v1/admin/management": {
      "get": {
        "summary": "List Admins / Employees",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "type",
            "in": "query",
            "description": "admin or employee, default is admin",
            "required": false,
            "example": "employee",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "phone": {
                            "type": "string"
                          },
                          "roles": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "id": {
                                  "type": "integer"
                                },
                                "name": {
                                  "type": "string"
                                },
                                "isActive": {
                                  "type": "integer"
                                }
                              },
                              "required": [
                                "id",
                                "name",
                                "isActive"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "links": {
                      "type": "object",
                      "properties": {
                        "first": {
                          "type": "string"
                        },
                        "last": {
                          "type": "string"
                        },
                        "prev": {
                          "type": "null"
                        },
                        "next": {
                          "type": "null"
                        }
                      },
                      "required": [
                        "first",
                        "last",
                        "prev",
                        "next"
                      ]
                    },
                    "meta": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "from": {
                          "type": "integer"
                        },
                        "last_page": {
                          "type": "integer"
                        },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "url": {
                                "type": "string",
                                "nullable": true
                              },
                              "label": {
                                "type": "string"
                              },
                              "active": {
                                "type": "boolean"
                              }
                            },
                            "required": [
                              "url",
                              "label",
                              "active"
                            ]
                          }
                        },
                        "path": {
                          "type": "string"
                        },
                        "per_page": {
                          "type": "integer"
                        },
                        "to": {
                          "type": "integer"
                        },
                        "total": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "current_page",
                        "from",
                        "last_page",
                        "links",
                        "path",
                        "per_page",
                        "to",
                        "total"
                      ]
                    }
                  },
                  "required": [
                    "data",
                    "links",
                    "meta"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "summary": "Add Admin / Employee",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": "{\r\n    \"name\": \"New Employee Name\",\r\n    \"email\": \"abdo@example.com\",\r\n    \"phone\": \"012233100\",\r\n    \"password\": \"password123\",\r\n    \"password_confirmation\": \"password123\",\r\n    \"roles\": [1, 3],\r\n    \"type\": \"admin\", // admin || employee\r\n    \"is_active\": true\r\n}"
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "phone": {
                          "type": "string"
                        },
                        "roles": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer"
                              },
                              "name": {
                                "type": "string"
                              },
                              "isActive": {
                                "type": "integer"
                              }
                            },
                            "required": [
                              "id",
                              "name",
                              "isActive"
                            ]
                          }
                        }
                      },
                      "required": [
                        "id",
                        "name",
                        "email",
                        "phone",
                        "roles"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "data"
                  ]
                },
                "example": {
                  "message": "Admin/Employee created successfully",
                  "data": {
                    "id": 628,
                    "name": "New Employee Name",
                    "email": "abdo@example.com",
                    "phone": "012233100",
                    "roles": [
                      {
                        "id": 1,
                        "name": "Support",
                        "isActive": 1
                      },
                      {
                        "id": 3,
                        "name": "Support",
                        "isActive": 1
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/admin/management/{entityId}": {
      "get": {
        "summary": "Show Admin / Employee Details",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "entityId",
            "in": "path",
            "description": "Admin or Employee ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "phone": {
                          "type": "string"
                        },
                        "roles": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer"
                              },
                              "name": {
                                "type": "string"
                              },
                              "isActive": {
                                "type": "integer"
                              }
                            },
                            "required": [
                              "id",
                              "name",
                              "isActive"
                            ]
                          }
                        }
                      },
                      "required": [
                        "id",
                        "name",
                        "email",
                        "phone",
                        "roles"
                      ]
                    }
                  },
                  "required": [
                    "data"
                  ]
                },
                "example": {
                  "data": {
                    "id": 1,
                    "name": "Test User",
                    "email": "test@example.com",
                    "phone": "540.368.4886",
                    "roles": [
                      {
                        "id": 1,
                        "name": "Support",
                        "isActive": 1
                      },
                      {
                        "id": 3,
                        "name": "Support",
                        "isActive": 0
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                },
                "example": {
                  "message": "User not found"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "summary": "Update Admin / Employee Details",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "entityId",
            "in": "path",
            "description": "Admin or Employee ID",
            "required": true,
            "example": "628",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": "{\r\n    \"name\": \"New Employee Name\",\r\n    \"email\": \"abdo@example.com\",\r\n    \"phone\": \"012233100\",\r\n    \"password\": \"password123\",\r\n    \"password_confirmation\": \"password123\",\r\n    \"roles\": [1, 3],\r\n    \"type\": \"employee\", // admin || employee\r\n    \"is_active\": true\r\n}"
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "phone": {
                          "type": "string"
                        },
                        "roles": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer"
                              },
                              "name": {
                                "type": "string"
                              },
                              "isActive": {
                                "type": "integer"
                              }
                            },
                            "required": [
                              "id",
                              "name",
                              "isActive"
                            ]
                          }
                        }
                      },
                      "required": [
                        "id",
                        "name",
                        "email",
                        "phone",
                        "roles"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "data"
                  ]
                },
                "example": {
                  "message": "Admin/Employee updated successfully",
                  "data": {
                    "id": 628,
                    "name": "New Employee Name",
                    "email": "abdo@example.com",
                    "phone": "012233100",
                    "roles": [
                      {
                        "id": 1,
                        "name": "Support",
                        "isActive": 1
                      },
                      {
                        "id": 3,
                        "name": "Support",
                        "isActive": 1
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                },
                "example": {
                  "message": "User not found"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "Delete Admin / Employee",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "entityId",
            "in": "path",
            "description": "Admin or Employee ID",
            "required": true,
            "example": "628",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                },
                "example": {
                  "message": "Admin/Employee deleted successfully"
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "message"
                  ]
                },
                "example": {
                  "message": "User not found"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [],
  "security": [
    {
      "bearer": []
    }
  ]
}